name = "MicroHH"
uuid = "9dba9f50-2dd2-405b-92a9-ad4528f9d99f"
authors = ["Chiel van Heerwaarden <chielvanheerwaarden@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
